# Generated by rebar3_nix
let
  fetchOnly = { src, ... }: src;
in
{
  builder ? fetchOnly,
  fetchHex,
  fetchgit,
  fetchFromGitHub,
  overrides ? (x: y: { }),
}:
let
  self = packages // (overrides self packages);
  packages = with self; {
    pg_types = builder {
      name = "pg_types";
      version = "0.6.0";
      src = fetchHex {
        pkg = "pg_types";
        version = "0.6.0";
        sha256 = "sha256-mUmkhJ3RNAj6JJq3t0Xg0t/blTKu4rlyIybjPNCCp3g=";
      };
      beamDeps = [ ];
    };
    opentelemetry_api = builder {
      name = "opentelemetry_api";
      version = "1.5.0";
      src = fetchHex {
        pkg = "opentelemetry_api";
        version = "1.5.0";
        sha256 = "sha256-9T7IoTN65KSH1DrInaS9OjyZ3fV2ZV0HHe7YtWotXdo=";
      };
      beamDeps = [ ];
    };
    fs = builder {
      name = "fs";
      version = "11.4.1";
      src = fetchHex {
        pkg = "fs";
        version = "11.4.1";
        sha256 = "sha256-3QCmHYnqwB0W0/xR1bDrXwci7448GjpUfNCGlX8yYKk=";
      };
      beamDeps = [ ];
    };
    erlandono = builder {
      name = "erlandono";
      version = "3.1.3";
      src = fetchHex {
        pkg = "erlandono";
        version = "3.1.3";
        sha256 = "sha256-K/yvZZwAMsW1zv1ILrvbohqyAdFXmlRIXgkZX8IJJXc=";
      };
      beamDeps = [ ];
    };
    epgsql = builder {
      name = "epgsql";
      version = "4.7.1";
      src = fetchHex {
        pkg = "epgsql";
        version = "4.7.1";
        sha256 = "sha256-tthrfcQshVWx1OIIgOUJnW1tBTFIAA4YjlSPmOTgGDY=";
      };
      beamDeps = [ ];
    };
    worker_pool = builder {
      name = "worker_pool";
      version = "6.5.3";
      src = fetchHex {
        pkg = "worker_pool";
        version = "6.5.3";
        sha256 = "sha256-vm1jIlxLtTj73brDiUfF3vUbFPv5CxPNnPDDNJSE+3M=";
      };
      beamDeps = [ ];
    };
    pgo = builder {
      name = "pgo";
      version = "0.20.0";
      src = fetchHex {
        pkg = "pgo";
        version = "0.20.0";
        sha256 = "sha256-LxHmZJzrOOVp71axa+HQSHSuWxGgKGcICigXzkI8aDs=";
      };
      beamDeps = [
        backoff
        opentelemetry_api
        pg_types
      ];
    };
    migraterl = builder {
      name = "migraterl";
      version = "0.5.0";
      src = fetchHex {
        pkg = "migraterl";
        version = "0.5.0";
        sha256 = "sha256-/O1wFlQGw/TSs3GjLyvaA4p4tTNVNuK5AwWcHy5rSMc=";
      };
      beamDeps = [
        epgsql
        erlandono
        fs
      ];
    };
    backoff = builder {
      name = "backoff";
      version = "1.1.6";
      src = fetchHex {
        pkg = "backoff";
        version = "1.1.6";
        sha256 = "sha256-zwz/+JlfsgVi+CLlzEfYzPZkxezcJqaEy+hcIl+dfDk=";
      };
      beamDeps = [ ];
    };
  };
in
self
