defmodule Ergon.DB do
  @moduledoc """
  Low-level database access for Ergon.

  Everything that touches `ergon.jobs` and `ergon.job_edges` lives here, so the
  PostgreSQL 18/19 temporal features it relies on are in one place. The SQL
  itself is in `priv/queries/` and loaded through `Ergon.SQL`. Higher-level
  modules (`Ergon.Worker`, the top-level `Ergon`) call these functions and
  never assemble SQL of their own.
  """
  alias Ergon.FSM.Outcome
  alias Ergon.{Job, SQL}

  @type error ::
          :empty_result | :would_create_cycle | {:job_not_found, integer()} | Exception.t()

  @doc """
  Insert a new job and return the materialised row, get-or-create.

  Uniqueness is enforced entirely by the database. The fingerprint is a
  deterministic hash of `(queue, worker, payload)` generated by the `ergon.jobs`
  table itself. For a unique job (`{:unique_for, seconds}`) the `ergon.enqueue`
  function sets a bounded `dedup_period`, so a second enqueue whose window
  overlaps a live copy hits the temporal uniqueness EXCLUDE and comes back as
  the *existing* job rather than an error. A non-unique job gets an empty
  `dedup_period`, which never overlaps, so duplicates always insert.
  """
  @spec insert(Ergon.NewJob.t()) :: {:ok, Job.t()} | {:error, error()}
  def insert(%Ergon.NewJob{} = job) do
    # 0 seconds means a non-unique job (empty dedup window, see insert.sql).
    dedup_seconds =
      case job.uniqueness do
        :not_unique -> 0
        {:unique_for, seconds} -> seconds
      end

    # job.payload (a map) is passed as-is, insert.sql binds it with an explicit
    # `$3::jsonb` cast, so Postgrex's jsonb extension JSON-encodes it once.
    params = [job.queue, job.worker, job.payload, job.max_attempts, dedup_seconds]

    with {:ok, %{rows: rows}} <- SQL.query({:jobs, :insert}, params) do
      first_row(rows, :empty_result)
    end
  end

  @doc """
  Atomically check out up to `limit` available jobs from `queue`, marking them
  `executing` and consuming an attempt via `FOR UPDATE SKIP LOCKED`.
  """
  @spec checkout(String.t(), pos_integer()) :: {:ok, [Job.t()]} | {:error, error()}
  def checkout(queue, limit) do
    with {:ok, %{rows: rows}} <- SQL.query({:jobs, :checkout}, [queue, limit]) do
      {:ok, Enum.map(rows, &Job.from_row/1)}
    end
  end

  @doc """
  Persist the outcome of a state transition for a single job.

  The update uses PostgreSQL 19's `UPDATE ... FOR PORTION OF` so the job's
  current validity window is closed at `now()` and a fresh row is written for
  the new state, preserving history for auditing instead of overwriting.
  """
  @spec apply_outcome(integer(), Outcome.t()) :: {:ok, Job.t()} | {:error, error()}
  def apply_outcome(job_id, %Outcome{} = outcome) do
    params = [job_id, Job.state_to_string(outcome.state), outcome.attempt, outcome.last_error]

    with {:ok, %{rows: rows}} <- SQL.query({:jobs, :apply_outcome}, params) do
      first_row(rows, {:job_not_found, job_id})
    end
  end

  @doc """
  Record a dependency edge (parent triggers child) in the workflow graph.
  Re-adding an existing edge is a no-op. Rejects an edge that would introduce a
  cycle (including a self-loop) with `{:error, :would_create_cycle}`, checked in
  the database via the `would_create_cycle` recursive reachability query.
  """
  @spec link(integer(), integer(), String.t()) :: :ok | {:error, error()}
  def link(parent_id, child_id, edge_type \\ "triggers") do
    with {:ok, %{rows: [[false]]}} <-
           SQL.query({:graph, :would_create_cycle}, [parent_id, child_id]),
         {:ok, _} <- SQL.query({:jobs, :link}, [parent_id, child_id, edge_type]) do
      :ok
    else
      {:ok, %{rows: [[true]]}} -> {:error, :would_create_cycle}
      {:error, _} = error -> error
    end
  end

  @doc """
  Cancel `job_id` and cascade the cancellation to every descendant still in a
  cancellable state (`available`/`executing`), discarding each via a proper
  valid-time transition. Returns the jobs actually discarded (terminal
  descendants are left untouched).
  """
  @spec cancel_cascade(integer()) :: {:ok, [Job.t()]} | {:error, error()}
  def cancel_cascade(job_id) do
    with {:ok, %{rows: rows}} <- SQL.query({:jobs, :discard_descendants}, [job_id]) do
      {:ok, Enum.map(rows, &Job.from_row/1)}
    end
  end

  @doc """
  Application-time time travel: the job versions whose `valid_period` contained
  `instant`, the truth about the world as of that moment.
  """
  @spec jobs_asof(DateTime.t()) :: {:ok, [Job.t()]} | {:error, error()}
  def jobs_asof(%DateTime{} = instant) do
    with {:ok, %{rows: rows}} <- SQL.query({:jobs, :asof}, [instant]) do
      {:ok, Enum.map(rows, &Job.from_row/1)}
    end
  end

  @doc """
  System-time time travel: what the database believed about each job as of
  `instant`, spanning live rows and the archived `ergon.jobs_history` twin.
  """
  @spec jobs_asof_system(DateTime.t()) :: {:ok, [Job.t()]} | {:error, error()}
  def jobs_asof_system(%DateTime{} = instant) do
    with {:ok, %{rows: rows}} <- SQL.query({:jobs, :asof_system}, [instant]) do
      {:ok, Enum.map(rows, &Job.from_row/1)}
    end
  end

  defp first_row([row | _], _when_empty), do: {:ok, Job.from_row(row)}
  defp first_row([], when_empty), do: {:error, when_empty}
end
