-module(ergon_db).
-moduledoc """
Low-level database access for Ergon.

Everything that touches `ergon.jobs` and `ergon.job_edges` lives here, so the
PostgreSQL 19 temporal features it relies on are in one place. The SQL itself is
in `priv/queries/` and loaded through `ergon_sql`. Higher-level modules
(`ergon_worker`, the `ergon` facade) call these functions and never assemble SQL
of their own.

## Two paths, deliberately separate

`checkout/2` and `apply_outcome/2` look symmetric and are not.

`checkout/2` is a plain `UPDATE ... FOR UPDATE SKIP LOCKED`. It marks jobs
`executing` and **increments `attempt`**, both inside the statement that takes
the lock, because that is what makes checkout atomic across concurrent workers.
It does not use `FOR PORTION OF`.

`apply_outcome/2` is `UPDATE ... FOR PORTION OF valid_period`, which closes the
job's current validity window at `now()` and writes a fresh row for the new
state, preserving history instead of overwriting it. It does **not** increment
`attempt`, since it persists the count the state machine already decided, and it is
where the retry backoff is applied, in SQL.

Collapsing the two would either double-count attempts or lose the history split.

## Retry backoff

The delay itself is `ergon.retry_backoff`, a database function, so a caller that
writes its own SQL still gets it. What lives here is only the tuning, read from
the application environment and passed as bind parameters:

```erlang
{ergon, [{ergon_db, [{retry_backoff, [
    {strategy, full_jitter},
    {base_ms, 1000},
    {cap_ms, 100000}
]}]}]}
```

`full_jitter` draws uniformly from `[0, ceiling]`, `equal_jitter` from
`[ceiling/2, ceiling]`, and `none` is the unjittered ceiling. The formulas, and
the article they come from, are documented at the function itself.

The defaults put the first retry's ceiling at 1 s and the hard ceiling at 100 s,
which are the endpoints Ergon has always had. What changed with jitter is the
*expected* wait: half the ceiling rather than all of it, so a job's full retry
budget is roughly halved. A host that wants the old total back doubles `base_ms`.
""".

-include_lib("ergon/include/ergon.hrl").

-export([
    insert/1,
    checkout/2,
    apply_outcome/2,
    link/2, link/3,
    cancel_cascade/1,
    jobs_asof/1,
    jobs_asof_system/1
]).

-export_type([db_error/0]).

-define(DEFAULT_EDGE_TYPE, ~"triggers").

%% Full Jitter is the article's own recommendation, and the base and cap are the
%% endpoints Ergon's curve has always had: a 1 s ceiling on the first retry and a
%% 100 s hard ceiling.
-define(DEFAULT_BACKOFF_STRATEGY, full_jitter).
-define(DEFAULT_BACKOFF_BASE_MS, 1_000).
-define(DEFAULT_BACKOFF_CAP_MS, 100_000).

%% ---------------
%% Jobs
%% ---------------

-doc """
Insert a new job and return the materialised row. Get-or-create.

Uniqueness is enforced entirely by the database. The fingerprint is a
deterministic hash of `(queue, worker, payload)` generated by the `ergon.jobs`
table itself, so it can never disagree with the columns. For a unique job the
`ergon.enqueue` function sets a bounded `dedup_period`, and a second enqueue
whose window overlaps a live copy trips the temporal uniqueness EXCLUDE, which
the function catches and answers with the *existing* job rather than an error. A
non-unique job gets an empty `dedup_period`, which never overlaps, so duplicates
always insert.
""".
-spec insert(new_job()) -> {ok, job()} | {error, db_error()}.
insert(#{queue := Queue, worker := Worker, payload := Payload} = New) ->
    #{max_attempts := MaxAttempts} = New,
    %% payload is bound to `$3::jsonb`; the driver's default json configuration
    %% expects an already-encoded value there, so encode it here.
    Params = [
        Queue,
        Worker,
        json:encode(Payload),
        MaxAttempts,
        ergon_new_job:dedup_seconds(New)
    ],
    maybe
        {ok, #{rows := Rows}} ?= ergon_sql:query({jobs, insert}, Params),
        first_row(Rows, empty_result)
    end.

-doc """
Atomically check out up to `Limit` available jobs from `Queue`, marking them
`executing` and consuming an attempt.

`FOR UPDATE SKIP LOCKED` means concurrent workers never contend for the same job.
Only live rows are considered, so a superseded version is never handed out twice.
""".
-spec checkout(binary(), pos_integer()) -> {ok, [job()]} | {error, db_error()}.
checkout(Queue, Limit) ->
    maybe
        {ok, #{rows := Rows}} ?= ergon_sql:query({jobs, checkout}, [Queue, Limit]),
        {ok, decode_jobs(Rows)}
    end.

-doc """
Persist the outcome of a state transition for a single job.

The update uses `UPDATE ... FOR PORTION OF`, so the job's current validity window
is closed at `now()` and a fresh row is written for the new state. The legality of
the transition is checked twice over: by `ergon_fsm:transition/2` before the call,
and by the `jobs_transition_guard` trigger regardless of caller.

On a retry the new `scheduled_at` comes from `ergon.retry_backoff`, tuned by the
`retry_backoff` configuration described in the module docs.
""".
-spec apply_outcome(ergon_job:job_id(), fsm_outcome()) -> {ok, job()} | {error, db_error()}.
apply_outcome(JobId, #{state := State, attempt := Attempt, last_error := LastError}) ->
    {Strategy, BaseMs, CapMs} = retry_backoff(),
    Params = [
        JobId,
        ergon_job:state_to_binary(State),
        Attempt,
        LastError,
        BaseMs,
        CapMs,
        strategy_to_binary(Strategy)
    ],
    maybe
        {ok, #{rows := Rows}} ?= ergon_sql:query({jobs, apply_outcome}, Params),
        first_row(Rows, {job_not_found, JobId})
    end.

-doc """
Cancel `JobId` and cascade to every descendant still in a cancellable state.

Each discard is a proper valid-time transition, so history is preserved and the
transition guard is satisfied. Terminal descendants are left untouched; the
return value is the jobs actually discarded.
""".
-spec cancel_cascade(ergon_job:job_id()) -> {ok, [job()]} | {error, db_error()}.
cancel_cascade(JobId) ->
    maybe
        {ok, #{rows := Rows}} ?= ergon_sql:query({jobs, discard_descendants}, [JobId]),
        {ok, decode_jobs(Rows)}
    end.

%% ---------------
%% Graph
%% ---------------

-doc "Record a `triggers` edge from `ParentId` to `ChildId`.".
-spec link(ergon_job:job_id(), ergon_job:job_id()) -> ok | {error, db_error()}.
link(ParentId, ChildId) -> link(ParentId, ChildId, ?DEFAULT_EDGE_TYPE).

-doc """
Record a dependency edge (parent triggers child) in the workflow graph.

Re-adding an existing edge is a no-op. An edge that would introduce a cycle,
including a self-loop, is rejected with `{error, would_create_cycle}`, decided in
the database by the `would_create_cycle` recursive reachability query.

The check and the insert run in one transaction **and** behind a
transaction-scoped advisory lock. The transaction alone is not enough: under READ
COMMITTED two concurrent calls adding opposite edges each see no cycle against
their own snapshot and both commit. The lock is what makes the pair mutually
exclusive. See `priv/queries/graph/lock_edges.sql`.

Returning `{error, _}` from inside the transaction commits rather than rolls
back, which is correct here: the rejection path has written nothing.
""".
-spec link(ergon_job:job_id(), ergon_job:job_id(), binary()) -> ok | {error, db_error()}.
link(ParentId, ChildId, EdgeType) ->
    ergon_repo:transaction(fun() ->
        maybe
            {ok, _} ?= ergon_sql:query({graph, lock_edges}, []),
            {ok, #{rows := [{false}]}} ?=
                ergon_sql:query({graph, would_create_cycle}, [ParentId, ChildId]),
            {ok, _} ?= ergon_sql:query({jobs, link}, [ParentId, ChildId, EdgeType]),
            ok
        else
            {ok, #{rows := [{true}]}} -> {error, would_create_cycle};
            {error, _} = Error -> Error
        end
    end).

%% ---------------
%% Time travel
%% ---------------

-doc """
Application-time time travel: the job versions whose `valid_period` contained
`Instant`, i.e. the truth about the world as of that moment.
""".
-spec jobs_asof(pg_timestamp()) -> {ok, [job()]} | {error, db_error()}.
jobs_asof(Instant) ->
    maybe
        {ok, #{rows := Rows}} ?= ergon_sql:query({jobs, asof}, [Instant]),
        {ok, decode_jobs(Rows)}
    end.

-doc """
System-time time travel: what the database believed about each job as of
`Instant`, spanning live rows and the archived `ergon.jobs_history` twin.
""".
-spec jobs_asof_system(pg_timestamp()) -> {ok, [job()]} | {error, db_error()}.
jobs_asof_system(Instant) ->
    maybe
        {ok, #{rows := Rows}} ?= ergon_sql:query({jobs, asof_system}, [Instant]),
        {ok, decode_jobs(Rows)}
    end.

%% ---------------
%% Helpers
%% ---------------

%% A row that does not match `from_row/1`'s eleven columns means a statement has
%% drifted from `ergon_job:column_list/0`. That must raise rather than be skipped,
%% because a silently shortened list reads as an empty queue. `from_row/1` has a
%% single clause over an eleven-element tuple, so the drift surfaces as a
%% `function_clause` on the first bad row; the generator does no filtering.
decode_jobs(Rows) -> [ergon_job:from_row(Row) || Row <- Rows].

first_row([Row | _Rest], _WhenEmpty) -> {ok, ergon_job:from_row(Row)};
first_row([], WhenEmpty) -> {error, WhenEmpty}.

%% Read per call rather than cached at boot, so a running node picks up a change
%% to the strategy without a restart. It is three proplist lookups on a retry
%% path that is already doing a round trip.
-spec retry_backoff() -> {retry_backoff_strategy(), pos_integer(), pos_integer()}.
retry_backoff() ->
    Env = proplists:get_value(retry_backoff, application:get_env(ergon, ?MODULE, []), []),
    {
        proplists:get_value(strategy, Env, ?DEFAULT_BACKOFF_STRATEGY),
        proplists:get_value(base_ms, Env, ?DEFAULT_BACKOFF_BASE_MS),
        proplists:get_value(cap_ms, Env, ?DEFAULT_BACKOFF_CAP_MS)
    }.

%% Clause-matched rather than defaulted, so a typo in sys.config fails loudly at
%% the first retry instead of quietly selecting a strategy nobody asked for. The
%% SQL function's own fallback is full_jitter, which no value reaching it from
%% here can trigger.
-spec strategy_to_binary(retry_backoff_strategy()) -> binary().
strategy_to_binary(full_jitter) -> ~"full_jitter";
strategy_to_binary(equal_jitter) -> ~"equal_jitter";
strategy_to_binary(none) -> ~"none".
